server.port=8009
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.r2dbc.url=r2dbc:h2:file:///./data/testdb
spring.r2dbc.username=sa
spring.r2dbc.password=admin

spring.sql.init.mode=always
spring.sql.init.platform=h2
